services:
  datadog-agent:
    image: datadog/agent:latest
    env_file:
    - docker.env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc/:/host/proc/:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
    - 127.0.0.1:8126:8126/tcp
    environment:
    - DD_APM_ENABLED=true
    - DD_APM_NON_LOCAL_TRAFFIC=true
    - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    - DD_HOSTNAME=test-rocksdb

  test-rocksdb-vanilla:
    build:
      context: .
      dockerfile: Dockerfile.vanilla
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE=test-rocksdb-vanilla
    - DD_ENV=local
    - DD_VERSION=1.0
    # https://docs.datadoghq.com/profiler/enabling/java/?tab=datadogprofiler#configuration
    - DD_PROFILING_ENABLED=true
    - DD_PROFILING_DDPROF_CPU_ENABLED=true
    - DD_PROFILING_DDPROF_WALL_ENABLED=true
    - DD_PROFILING_DIRECTALLOCATION_ENABLED=true
    - DD_PROFILING_DDPROF_ENABLED=true
    # native stack traces
    - DD_PROFILING_DDPROF_CSTACK=dwarf
    depends_on:
    - datadog-agent

  test-rocksdb-patched:
    build:
      context: .
      dockerfile: Dockerfile.patched
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE=test-rocksdb-patched
    - DD_ENV=local
    - DD_VERSION=1.0
    # https://docs.datadoghq.com/profiler/enabling/java/?tab=datadogprofiler#configuration
    - DD_PROFILING_ENABLED=true
    - DD_PROFILING_DDPROF_CPU_ENABLED=true
    - DD_PROFILING_DDPROF_WALL_ENABLED=true
    - DD_PROFILING_DIRECTALLOCATION_ENABLED=true
    - DD_PROFILING_DDPROF_ENABLED=true
    # native stack traces
    - DD_PROFILING_DDPROF_CSTACK=dwarf
    depends_on:
    - datadog-agent

  test-rocksdb-pr-13049:
    build:
      context: .
      dockerfile: Dockerfile.pr-13049
    environment:
    - DD_AGENT_HOST=datadog-agent
    - DD_SERVICE=test-rocksdb-pr-13049
    - DD_ENV=local
    - DD_VERSION=1.0
    # https://docs.datadoghq.com/profiler/enabling/java/?tab=datadogprofiler#configuration
    - DD_PROFILING_ENABLED=true
    - DD_PROFILING_DDPROF_CPU_ENABLED=true
    - DD_PROFILING_DDPROF_WALL_ENABLED=true
    - DD_PROFILING_DIRECTALLOCATION_ENABLED=true
    - DD_PROFILING_DDPROF_ENABLED=true
    # native stack traces
    - DD_PROFILING_DDPROF_CSTACK=dwarf
    depends_on:
    - datadog-agent
